site_name: ${{values.component_id}}
site_description: ${{values.description}}
repo_url: https://github.com/codaqui/backstage

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

theme:
  name: material
  font: false
