name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-and-test:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.1'
          cache: 'yarn'

      #   - name: Cache Yarn cache
      #     uses: actions/cache@v4
      #     with:
      #       path: ~/.yarn/cache
      #       key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #       restore-keys: |
      #         ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run quality check
        run: yarn quality:check

      - name: Run tests
        run: yarn test:all
